# Generated by Django 2.2.2 on 2019-06-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yelper_app', '0002_auto_20190627_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='yelper_app.Review'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='login_registration_app.User'),
        ),
    ]
